name: coordinates_opener
description: "Open any coordinates in google maps."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../packages/shared
  google_maps_flutter: ^2.9.0
  separate: ^1.0.3
  pointer_interceptor: ^0.10.1+2
  provider: ^6.1.2
  collection: ^1.18.0
  lottie: ^3.1.3
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  firebase_crashlytics: ^4.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/coordinates_opener/assets/loading_animation.json
